### ISSUE TITLE
Form Customization - set default not working with radio options

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10954]
bobray created Redmine issue ID 10954

Now works with text TVs but not radio options.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6333

**Comment by BobRay** [comment]
bobray submitted:

I still can't make this work for radio options or a drop-down list (no default value is set): Input Option Values for tv1: red||blue||green The rule shows as follows: tv1
resource/update (tried resource/tvs also)
tvDefault
green I set group to none and left containing panel blank. Cleared all caches, cookies, and permissions . Note: it didn't show for a text TV until I flushed all sessions.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
