### ISSUE TITLE
Clear cache sometimes shows an empty console.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11057]
bobray created Redmine issue ID 11057

This has been going on for quite a while &#8211; I was hoping it would go away. Sometimes when I select Clear Cache from the main menu, I get an empty console with the OK button active. I can wait a long time, but all it shows is "Console running . . ." If I select Clear Cache again, it usually behaves normally, but sometimes I have to do it three times to see anything in the console. When this happens, I don't think the cache is actually cleared.

**Comment by splittingred** [comment]
splittingred submitted:

Should be solved now with introduction of new MODx.Console.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.

**Comment by johnywhy** [comment]
johnywhy submitted:

i'm still getting this in a 2.1 install that was recently upgraded to 2.2.

**Comment by BobRay** [comment]
bobray submitted:

I'm seeing this again regularly in 2.2.0-pl2 both on localhost and remote.
