### ISSUE TITLE
New user's password doesn't show

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1119]
bobray created Redmine issue ID 1119

When a new user is created and saved, the user's password is blank in the popup box.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5879.

**Comment by BobRay** [comment]
bobray submitted:

Still seeing this in r5917 with these settings: X Show new password on the screen
X Let me specify the password

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed. (filed separate issue on modifying existing user's pwd).
