### ISSUE TITLE
TV - "set to default" doesn't work for radio buttons, DD lists, checkboxes

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1121]
bobray created Redmine issue ID 1121

For radio box TV's "Set to Default" sets them to the first item, rather than the default item. "Set to Default" does nothing to drop-down list boxes (and their defaults don't seem to be set in the first place). I also haven't been able to get checkbox TVs set to a default in the first place, but it's probably because I'm doing it wrong.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5880

**Comment by BobRay** [comment]
bobray submitted:

Now works for DD lists, but I'm still seeing it with checkboxes and radio buttons (maybe I'm doing something wrong): Input Option Values:
/images/image1||/images/image2||/images/image3 Default Value:
@INHERIT /images/image3 Default value is not set and "Set to Default" sets it to the first one.

**Comment by BobRay** [comment]
bobray submitted:

This is still really flaky for me. If you go back and forth between editing a TV and the TV tab of a resource, sometimes the default is set right, sometimes wrong, and sometimes not set at all for radio buttons and checkboxes (and occasionally for DD lists). For one thing, I don't think the cache is being cleared properly when the TV is saved, although clearing the cache manually doesn't always solve the problem. "Set to Default" for Radio buttons and checkboxes sometimes works, but usually, it sets the first option regardless of what the default is. It seems to work better with this style: one==1||two==2 (versus one||two) as long as you use 1 or 2 for the default rather than one or two, but either way, it often doesn't work. I spent about two hours messing with this and can't find any reliable pattern to the errors. In addition, returning to a TV with the Type set to Radio Options, the Type is sometimes shown as Text even though it was never set to Text and the TV still displays as Radio Options on the Create/Edit Resource page.

**Comment by BobRay** [comment]
bobray submitted:

Closing this. I'll create new issues when I come up with something that can be reliably reproduced.
