### ISSUE TITLE
Problems with "Export Lexicon"

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1226]
bobray created Redmine issue ID 1226

There are several problems with exporting a Lexicon. 1. The topic is shown by number rather than name. If you use the drop-down to select the name ("default" in my test), the exported file is empty. 2. Long lines are wrapped in the resulting file (an OA character is inserted at the wrap point, at least on Windows Vista). 3. On Vista, the file isn't saved to core/export/lexicon as the text in the popup suggests. It goes to wherever you last saved a file in Vista, though you can browse to wherever you want it.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5865. Nothing I can do about line endings; apparently that's a PHP fwrite issue.

**Comment by BobRay** [comment]
bobray submitted:

Still some problems here. If you export a namespace other than core, you still see the core topics (in fact, this happens throughout LM &#8211; every namespace shows the core topics and there's no way to see the topics of another namespace that I can find) .Still saves to the last dir I used in Vista (probably a Vista or FF problem that can't be solved). lines like this: $_lang &#91;&#39;wrote&#39;&#93; = "wrote:\n\n"; get spilt at the /n characters

**Comment by BobRay** [comment]
bobray submitted:

Can't export a topic in a non-core namespace. 1. Install a 3PC..
2. Click on Export Topic.
3. Select the 3PC's namespace Only core topics are shown. Still seeing this in r5917 (FF 3.5.3).
