### ISSUE TITLE
Traditional installations additional permissions required 

### ISSUE THREAD

**Issue by eerne** [modxbot/migrate#1315]
eerne created Redmine issue ID 1315

On my shared host installation only succeeds if all directories are writable. see conclusion of this thread: http://modxcms.com/forums/index.php?topic=37177.msg230516#msg230516

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5905

**Comment by eerne** [comment]
eerne submitted:

beta5 still hangs at setup/index.php?action=options and just continues the installation process if all directories are writable. http://modxcms.com/forums/index.php/topic,37177.msg260100.html#msg260100

**Comment by opengeek** [comment]
opengeek submitted:

I can't reproduce this at all, with beta5 or the current development branch.

**Comment by splittingred** [comment]
splittingred submitted:

Probably an issue of PHP or Apache being run with the wrong user, or a user without proper permissions. Since it's a server config issue, closing this ticket.

**Comment by eerne** [comment]
eerne submitted:

it was a total user (me) error, because I rename config.inc.tpl to config.inc.php reading the install instructions, I was looking for which dirs to give write permission
 http://svn.modxcms.com/docs/display/revolution/Fresh+Installation
4. Create a blank file "/core/config/config.inc.php" and make it writable. I am so used (from evo) to rename config.inc.tpl to config.inc.php but this file is not blank so the installation process stopped with a blank page. please close this issue
