### ISSUE TITLE
In System Settings, "Clear Filter" has to be clicked twice

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1377]
bobray created Redmine issue ID 1377

The first click has no effect.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6083

**Comment by BobRay** [comment]
bobray submitted:

Fixed.

**Comment by BobRay** [comment]
bobray submitted:

I'm still seeing this in FF 3.5.5 and Chrome 3.0 in r6126

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
