### ISSUE TITLE
"Duplicate Children" shows in right-click duplicate dialog for containers with no children

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1468]
bobray created Redmine issue ID 1468

Not sure if this is worth fixing but it might look more polished if it were.

**Comment by splittingred** [comment]
splittingred submitted:

This must have been fixed in a prior rev; doesn't occur now.

**Comment by BobRay** [comment]
bobray submitted:

Still happens for me in FF3/Vista when duping any childless container document with right click.
