### ISSUE TITLE
Tag output filter doesn't work with some nested tags

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1476]
bobray created Redmine issue ID 1476

In nested tags, the inner tags are processed (these are valid tags). [[~[[ChunkLink? &status=`[ &#91;++site_status&#93; ]`]]:tag]] is
rendered as: [ &#91;~5&#93; ](snippet returns 5) [[ChunkLink? &status=`[ &#91;~5&#93; ]`:tag]] is
rendered as 5 It would be nice to use this feature for docs and tutorials and have it simply render the original tag. Putting the :tag filter in every tag (or more than one tag) in a nested situation usually produces no output at all.

**Comment by splittingred** [comment]
splittingred submitted:

This might have been fixed. But first off, your syntax for the 2nd example should be: [[$chunkLink:tag? &status=`[[~5]]`]] The filter must be before the ?

**Comment by BobRay** [comment]
bobray submitted:

I still can't get either of those example tags to render as written. Maybe I'm putting the :tag in the wrong places, but I've tried everything I can think of. Either the inner tags are processed, I get no output at all, or I see entity codes in the output.
