### ISSUE TITLE
Quirks for TVs with Image and HTML Tag 

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1589]
bobray created Redmine issue ID 1589
1. TVs with an Image output type sometimes get empty attributes included in the tag (maybe if they are entered and later changed to empty). Often, they get stuff like id="" style="" etc. inserted in the tag. It may be because the param names persist in the display_params field of the site_templvars table even if empty. Maybe they should be cleared when empty or the parser needs to do a better job of identifying empty ones. display_params field: &alttext=&hspace=&vspace=&borsize=&align=none&name=&class=My Class&id=&style=&attributes= The code in image.php doesn't test for empty params and sets the variables (which are output, empty or not): $alt= htmlspecialchars($params &#91;&#39;alttext&#39;&#93; );
   $class= $params &#91;&#39;class&#39;&#93; ;
   $style= $params &#91;&#39;style&#39;&#93; ;
   $attributes= $params &#91;&#39;attrib&#39;&#93; ; When those lines are commented out, the empty vars are still output. 2. A TV with the output set to HTML Tag and an empty ID field gets an id of tvtv followed by the TV name. (e.g. id="tvtvMyTV"). The code in the renders/web/output folder only adds one tv prefix so the other must be added somewhere else (can't find where). This bug seems to be consistent. It should be possible to have a HTML tag with no id attribute.

**Comment by BobRay** [comment]
bobray submitted:

None of this seems to occur in 0.9.6.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5288

**Comment by BobRay** [comment]
bobray submitted:

TVs with Output Type set to HTML Tag and a blank ID field still get an ID of "tv" followed by the TV name.
