### ISSUE TITLE
Editing extra TV fields doesn't make the TV dirty

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1590]
bobray created Redmine issue ID 1590

For the extra fields that drop down for HTML TAG, Image, etc. Output Types, loading the TV for editing and changing those fields doesn't set the dirty flag and the TV can't be saved (even if you click outside the area). To save, you need to edit one of the main fields to make the TV dirty. Also, once the TV has been saved, it remains dirty (even though it's not) and the Save button is active until you load something else and come back.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5142

**Comment by BobRay** [comment]
bobray submitted:

I'm still seeing this one. To reproduce: 1. Set TV Output type to Image
2. Save TV
3. Go somewhere else
4. Edit original TV
5. Change Class, ID, Style, Name, etc.
6. Try to save. Also, TV's remain dirty after saving.
