### ISSUE TITLE
Top Menu fubared in IE7

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1660]
bobray created Redmine issue ID 1660

Top menu drop-down items are behind the left panel and scrunched above the right panel in IE7 so Manager is largely unusable.

**Comment by BobRay** [comment]
bobray submitted:

Actually, drop-downs appear behind both panels. Here's a screencast: http://www.screencast.com/users/BobRay/folders/Jing/media/0d511256-ea5e-4d7e-bc90-ee46bdf1e49b

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4957.

**Comment by maxpiepenbrink** [comment]
mido submitted:

same problem in beta 1

**Comment by BobRay** [comment]
bobray submitted:

I can't test the other IE7 fixes because I'm still seeing this one (IE7 Vista Ultimate). It looks like a Z-index problem.

**Comment by splittingred** [comment]
splittingred submitted:

Added a fix to 6357, can someone confirm?

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed!
