### ISSUE TITLE
Blank console on installation in FF3

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1793]
bobray created Redmine issue ID 1793

The package installs properly and the "Console running . . . message appears but nothing more. The ok button is live at the end of the installation.

**Comment by splittingred** [comment]
splittingred submitted:

Bah. Try clearing your cache. Could you attach the renegade package?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4664. Made sure final console body was updated with end message.

**Comment by BobRay** [comment]
bobray submitted:

I'm still getting the blank console some of the time and uninstall often gives me a view of the readme.txt file in the console (I've seen this on and off for a while). You can pretty much count on me having done a build/setup and clearing all caches before reporting anything. That said, I think there is something goofy with the package, though I can't see what other than that it has no lexicon. The offending package is here: http://svn.modxcms.com/svn/modx-components/thermx/trunk
