### ISSUE TITLE
Quirks in snippet properties grid

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1950]
bobray created Redmine issue ID 1950

No property fields can be edited with double-click.The Value field on yes/no items does have a dropdown that appears on double-click, but it only contains one item and is dead. For Yes/no items in create property, the user can type anything in the box. Should probably have a yes/no dropdown eventually. There's some funkiness in saving and what get's set as dirty. Sometimes, the snippet "save" button is active (not grayed out), but doesn't do anything. Sometimes, you can alter a property, save it (with the propertiy save button) &#8211; the snippet save button will remain gray but the change won't be saved (if you go to another snippet and come back, your change is gone). Sometimes, the only way to reliably save property changes is to save the property, go to the general tab, make a change in the snippet and then use the snippet save button. You can change all the fields of a property using right-click "update", save each in turn, and the snippet will not be dirty. If you navigate away and come back, none of your changes will be there.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4370

**Comment by BobRay** [comment]
bobray submitted:

As of 4373: In both IE7 and FF3: Type still shown as "combo-boolean" in the grid for Yes/No type fields. Double-click will only edit Yes/No and list value fields. Double-clicking on any other fields (except the type field) makes them flash white but nothing else. Maybe they're not meant to be edited, but then they probably shouldn't flash. I see that a Yes/No property with limited input can be implemented as a list type, but I feel strongly that for naive users, there should be a pure Yes/No type that operates as it does in System Settings, preferably with a Yes/No dropdown for setting the value on creation or update (combo-boolean could be another choice, but I don't see the need for it as long as we have "list"). Currently, using Update or Create property, the user can enter any value at all for Yes/No Fields and giving a value of "True" or "Yes" for Yes/No fields results in "no" (only "1" works). User can change a setting, click on the update dialog's "save" button and navigate away from the snippet without anything being saved. In fact, the user could edit many property settings, clicking on save each time and then lose all work by navigating away without using the Snippet's "save" button. Hopefully, there's some way to make the individual property dialog button do a permanent save.

**Comment by BobRay** [comment]
bobray submitted:

One more issue: If you have a long list of properties, and scroll up and down it, when you select "update," the update dialog will often be off the screen and you have to scroll to find it. Happens in both IE7 and FF3.

**Comment by BobRay** [comment]
bobray submitted:

Integer is missing as a choice in the drop-down list. Can't sort entries.

**Comment by BobRay** [comment]
bobray submitted:

Still some stuff to beat down here.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4388.

**Comment by BobRay** [comment]
bobray submitted:

Fixed.
