### ISSUE TITLE
smarty cache path conflicts

### ISSUE THREAD

**Issue by redman** [modxbot/migrate#2154]
redman created Redmine issue ID 2154

as discussed at http://modxcms.com/forums/index.php/topic,27843.msg169103.html#msg169103 , smarty should respect contexts for caching its templates so as to prevent conflicts.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3923

**Comment by redman** [comment]
redman submitted:

This isn't quite fixed. Line 52 of modSmarty.class.php needs changing from:
$this->compile_dir = $modx->cachePath . 'mgr/smarty/';
to
$this->compile_dir = $modx->cachePath . $modx->context->get('key') . '/smarty/';

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3935.
