### ISSUE TITLE
Cosmetic: Save successful message (prevent horizontal scrollbars)

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#2694]
pixelchutes created Redmine issue ID 2694

Pretty trivial guys, but I noticed that when the "SUCCESS! Save successful" overlay message appears on the screen, the overlay causes horizontal scrollbars to show up. They then disappear as soon as this message is gone. I would think a pretty simple update could prevent the horizontal scrollbars while the Success message is present.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

NOTE: Forgot to mention this occurs in Revo 2.0.0-pl and greater...

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/ac658c4aa403d191d86fe4fcd5a2b64157da4b1b

**Comment by pixelchutes** [comment]
pixelchutes submitted:

I just updated to 2.0.5-pl (Advanced) but am still seeing this issue. I double-checked "manager/templates/default/css/index.css" being served matches the commit you referenced, too...even confirmed it made it into: "manager/templates/default/css/modx-min.css"

(please see attached images)

Tested on OS X 10.6.5, FF 3.6.13 and Safari 5.0.3...

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Here's one more:

**Comment by pixelchutes** [comment]
pixelchutes submitted:

I just tried a fresh install of 2.0.5-pl Advanced and performed a few tests:
- When editing "Home" _Resource_, I can reproduce this issue during the "Please Wait. Saving..." message (whether scrolled down before saving, or not). NOTE: The "Success" message that follows no longer presents this issue, however.
- When editing "BaseTemplate" _Template_, I cannot reproduce this issue.
- When creating/editing a _Chunk_, I cannot reproduce this issue.
- When creating/editing a _Snippet_, I cannot reproduce this issue.
- When creating/editing a _Template Variable_, I cannot reproduce this issue.
- When creating/editing a _Plugin_, I cannot reproduce this issue.

Seems to be something related to editing Resources on my end, and only during the "Please Wait" message...see my above screenshot (modx_revo_saving_scrolled_down.jpg) to view issue with overlay not covering the current viewport when scrolled down prior to saving.

The horizontal scrollbar is also showing up during the "Are you sure you want to logout?" prompt, but only when I am editing a Resource...

**Comment by splittingred** [comment]
splittingred submitted:

I just simply can't reproduce this. Since it's such a trivial issue, closing.
