### ISSUE TITLE
Changing parent does not change context of children

### ISSUE THREAD

**Issue by gerritvanaaken** [modxbot/migrate#2737]
gerritvanaaken created Redmine issue ID 2737

I use several frontend contexts for several sub-domains. The default "web" context is empty.

When I create a new document resource via the global dropdown menu, it gets the context "web", which is fine. However, if I choose the parent page of my new resource via clicking on the page tree, it gets tricky: The desired parent resource is part of a different context! But defining a parent resource does not change the context of the child resource.

I think the context of a parent page should always be inherited to its children.

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed in a prior bug report.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

It’s not fixed in 2.0.5! Please take a look:

http://screencast.com/t/eEnCY3MVOXB

(Context gets not inherited from parent element!)

**Comment by eerne** [comment]
eerne submitted:

Hi, I just want to confirm this issue on 2.0.5pl

It also happens, when you right-click "Create / Create Document" and "Quick Create / Document" when it's not in the web context.

The only one that works is "Duplicate Resource" (afaik)

Thanks for looking into it.

**Comment by SebastienDaniel** [comment]
Askarii submitted:

Enrique Erne wrote:

> Hi, I just want to confirm this issue on 2.0.5pl
> 
> It also happens, when you right-click "Create / Create Document" and "Quick Create / Document" when it's not in the web context.
> 
> The only one that works is "Duplicate Resource" (afaik)

Eerne and I just reproduced the bug voluntarily, so I confirm everything he said.
I'll also add that if a resource is created in the "web" context, it can be dragged to other contexts and used properly.
So dragging works fine.

This issue appears to be linked to:
http://bugs.modx.com/issues/3034

**Comment by opengeek** [comment]
opengeek submitted:

This is not critical; sorry was updating wrong ticket when setting to critical.

**Comment by opengeek** [comment]
opengeek submitted:

Actually, this is critical and related to #3034

**Comment by opengeek** [comment]
opengeek submitted:

Fixed via #3034

https://github.com/modxcms/revolution/commit/3952453f8e9608e9998cf1935040513ce24f634c

**Comment by opengeek** [comment]
opengeek submitted:

It appears that if you change the parent of a Resource to one in a different context, it's children's context_key is not updated. This works when dragging Resources to a new parent in a different Context, just not when selecting a new parent outside the context in the Edit Resource action.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed in develop—see commit details at https://github.com/modxcms/revolution/compare/9ea2233ae4...9861d91944

This includes a new feature in xPDO which allows iterating aggregate and composite relations by alias using an xPDOIterator instance. This will eliminate memory issues when traversing large sets of Children recursively.

**Comment by opengeek** [comment]
opengeek submitted:

This is ported back for 2.1.4-pl release now, which will be available shortly.

**Comment by juro** [comment]
juro submitted:

This is also related to #4918. Unfortunately this commit still doesn't fix problems dragging resources in the tree.
/core/model/modx/processors/resource/sort.php performs access rights check on every visible node and also saves every visible node (except children of dragged node), regardles whether it has changed or not. This leads to incorrect access denied errors and unnecessary database updates (calling save() on every node).
Node should be added to modifiedNodes array only if either parent, context or order has changed.

Please reopen and correct this issue in 2.1.4.
