### ISSUE TITLE
Image TV does not save correct path when re-editing document

### ISSUE THREAD

**Issue by borizz** [modxbot/migrate#3197]
borizz created Redmine issue ID 3197

After selecting a image in an image TV, the path of the image is saved correcly. However after editing the same document again without editing the TV, the path is changed and the image will not be shown on the front of the website.

Steps to reproduce:
1. Create an image template variable and assign it to a template
2. Edit a document with the given template
3. Select an image with via the image browser for the image tv , path should now start with /assets/files/
4. save the document
5. Edit the same document as in step 2
6. View the image tv, the image is shown, but the filemanager_url (/assets/files/) has been stripped from the value 
7. Save the document.
8. The Image path is now saved without "/assets/files", this is different from the first save which included "/assets/files/"

This is confusing, because you cannot reliably show a picture with the image TV and changed filemanager paths. A patch for this bug is attached.

MODx Version: MODx Revolution 2.0.6
Settings:
filemanager_path : {assets_path}/files
filemanager_path_relative: false
filemanager_url: /assets/files
filemanager_url_relative: true

**Comment by splittingred** [comment]
splittingred submitted:

Needs a test in 2.0.6-pl.

**Comment by borizz** [comment]
borizz submitted:

This has been tested (only) against 2.0.6-pl, but this version was not listed under "Affects Revolution Version:" that's why I chose 2.0.5-pl.

**Comment by multimedia** [comment]
multimedia submitted:

i have tested these patches in 2.0.6-pl but doesnt work for me. altough my situation might be different, the problem remains that showing the phpthumb from an image tv is broken. (it worked fine in 2.0.5)

default modx 2.0.5. install with multple context.
defined the filemanager_path and filemanager_url in system settings and set it for each context (since each context uses its own images folder)

h1. MODx 2.0.5 

_systemsettings_
filemanager_path = /var/www/vhosts/local.crowneast.nl/httpdocs/assets/images/default/
filemanager_path_relative = dont know (did it exist in 2.0.5?)
filemanager_url = assets/images/default/
filemanager_url_relative = dont know (did it exist in 2.0.5?)

_context 'test'_
filemanager_path = /var/www/vhosts/local.crowneast.nl/httpdocs/assets/images/test/
filemanager_url = assets/images/test/

h1. MODx 2.0.6 

after updating to 2.0.6. the filemanager gave an error and could not show the folder. setting filemanager_path_relative to No fixed this problem. so the filemanager works fine.

_systemsettings_
filemanager_path = /var/www/vhosts/local.crowneast.nl/httpdocs/assets/images/default/
filemanager_path_relative = No
filemanager_url = assets/images/default/
filemanager_url_relative = Yes

_context 'test'_
filemanager_path = /var/www/vhosts/local.crowneast.nl/httpdocs/assets/images/test/
filemanager_url = assets/images/test/

When selecting an image for an image tv assigned to a resource in the context 'test' from the folder assets/images/test/level1/ the following happens:
- input value = assets/images/test//level1/logo.gif (notice the double / between test and level1 which should not be there)
- url from phpthumb generated thumbnail = http://www.domain.com/connectors/system/phpthumb.php?h=150&w=150&src=/level1/logo.gif&wctx=test (works fine, also wctx value is passed correctly)
- saving resource
- reselecting same resource (opening resource for editing) the input value is the same, but the thumbs dont show
- using the "Find Broken Images" in firefox shows the following url: http://www.domain.com/connectors/system/phpthumb.php?h=150&w=150&src=assets/images/test//level1/logo.gif (notice the same filepath as the input value, which is different from the working thumbnail before, also no wctx value is passed)
- manualy loading the thumbnail in the browser with modified url doesnt show the thumbnail: http://www.domain.com/connectors/system/phpthumb.php?h=150&w=150&src=/level1/logo.gif
- adding the right wctx value in the browser and it shows the thumb: http://www.domain.com/connectors/system/phpthumb.php?h=150&w=150&src=/level1/logo.gif&wctx=test

it seems that in the image.tpl line 4 it takes the {$tv->value} to pass to phpthumb, this value is not correct (see above)
in image.tpl line 25 it uses data.url and passes wctx value $ctx for the context.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/290dd4c810b6d969c22e7afeb8978d91637afe23

**Comment by rubenk** [comment]
rubenk submitted:

I am afraid this issue still exists in Revolution-2.0.7-pl. I have a simmilar, but I think even the same problem. I have multiple contexts from which I have set the file_manager_path setting different in each context. After selecting an image, the correct URL is shown in the image field. This is the URL after the file_manager_path, so this is good. After saving and refreshing the page I see that the first / is removed, which breaks the image.

**Comment by rubenk** [comment]
rubenk submitted:

I think their is another problem. When reloading the page as I described above, the &wctx=contextname isn't added to the url. This prevents loading the right url-path.
