### ISSUE TITLE
Updating user's Date of Birth in manager gives error when manager date format is d-m-Y and day is more than 12

### ISSUE THREAD

**Issue by vladski** [modxbot/migrate#3287]
vlado12345 created Redmine issue ID 3287

If setting manager_date_format = d-m-Y when updating user details in manager if I select date like 29-12-2010 where day is more than 12 I get error: _Please State The Birthdate In Mm/dd/yyyy Format_.

The error is happening in script _validation.php where on line 80:

<pre>
$scriptProperties['dob'] = str_replace('-','/',$scriptProperties['dob']);
if (!$scriptProperties['dob'] = strtotime($scriptProperties['dob']))
            $modx->error->addField('dob',$modx->lexicon('user_err_not_specified_dob'));
</pre>

According to PHP manual for strtotime: _Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components: if the separator is a slash (/), then the American m/d/y is assumed; whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed._

So after replacement date 29-12-2010 becomes 29/12/2010 and PHP thinks 29 is month and strtotime returns false.

Vlad

**Comment by vladski** [comment]
vlado12345 submitted:

Actually even if there is no error day and month are swapped.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/d0df829a068121d83112c460efde573a16f68dc4

**Comment by opengeek** [comment]
opengeek submitted:

For 2.1.4: https://github.com/modxcms/revolution/commit/907f86d61f805bfe017413ded1f8d95291cd9a97

**Comment by ghost** [comment]
sottwell submitted:

Still getting this error in 2.2.4

The date picker generates in invalid format, and the live error message specifies a different required format while manually entering a date than the error on attempted save.

**Comment by eprochasson** [comment]
eprochasson submitted:

The bug is also reported in http://tracker.modx.com/issues/7631

There is a pull request here :
https://github.com/modxcms/revolution/pull/370
