### ISSUE TITLE
New Content Types always binary, even when binary=no is selected

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#4146]
jrotering created Redmine issue ID 4146

When a new Content Type is created, the "binary" selection is ignored, and binary is always initially set to yes.  

Once the content type has been created you can Change the type from binary to non-binary, but it seems to require a cache clearing before it takes effect.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/1aea734fd666b0f372526dcbbbfb41e098166d6d

**Comment by sdwespi** [comment]
sdwespi submitted:

It looks like this bug still exists in 2.1.3 - new content types still default to binary, but changing them doesn't require refreshing the cache.

**Comment by opengeek** [comment]
opengeek submitted:

Confirmed; this does appear to still be an issue in 2.1.3-pl.

**Comment by opengeek** [comment]
opengeek submitted:

This also still affects latest develop.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/811b2d77919d9a20ee70a933a4a68d1b94ff5e88
