### ISSUE TITLE
Path error when created/updating modStaticResource with File Manager Path set

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4362]
ncrossland created Redmine issue ID 4362

On a site with system setting File Manager Path set to "assets"
1. Create a new modStaticResource resource
2. In the "Static resource" field, choose a file located several folder levels deep, e.g. assets/files/uploadedfile.html
3. Click OK

When the file path appears, the inital slash is missing, e.g. it appears and is stored as

assetsfiles/uploadedfile.html

At step 2, the file browser that appears is not respecting the File Manager Path setting, but I'm not sure if this is by design or not.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Have you tried adding an additional slash forward to the filemanager_path and filemanager_url values?

<pre>
filemanager_path: assets/
filemanager_url: assets/
</pre>

**Comment by ncrossland** [comment]
ncrossland submitted:

It occurs with or without the trailing slash. The slash is not required elsewhere for paths affected by filemanager_path / filemanager_url

**Comment by gadamiak** [comment]
gadamiak submitted:

Just a note: according to "note 3":http://bugs.modx.com/issues/4208#note-3 on issue #4208 @filemanager_@ paths should have a trailing forward slash.

**Comment by ncrossland** [comment]
ncrossland submitted:

Would be helpful if the contextual help for this setting noted that -- however this bug occurs whether the slash is present or not...

**Comment by splittingred** [comment]
splittingred submitted:

This should have been fixed in 2.1-rc3, is it working now?

**Comment by ncrossland** [comment]
ncrossland submitted:

No, I still see this on RC3, and on further testing it happens whether or not filemanager_path is set or not. The first slash of the path inserted is always missing.

**Comment by splittingred** [comment]
splittingred submitted:

Sorry Nick, I can't replicate this at all, on multiple tests.

**Comment by lukemcd** [comment]
lukemcd submitted:

I am using a fresh 2.1 RC3 install and am experiencing this issue as well. If you like I can send you log in info Shaun.

**Comment by splittingred** [comment]
splittingred submitted:

Luke, what are your filemanager_path settings set to?

**Comment by lukemcd** [comment]
lukemcd submitted:

Shaun, the filemanager_path setting is blank. This issue occurs whether I give it a value or not.

**Comment by lukemcd** [comment]
lukemcd submitted:

This is a sample of what gets put in the Static Resource field when I select a file (note no slash between assets and content):
assetscontent/documents/board/BoardMemberApplication.pdf

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this either. As long as the field is blank and filemanager_path_relative is set to Yes, it works fine. If blank and the relative option is set to no, then MODX Browser shows "Please select a valid directory". Same if I provide a relative path such as "assets/" and set the relative option to no.

**Comment by lukemcd** [comment]
lukemcd submitted:

I just did a fresh installation of RC3, didn't change any settings, and still have this issue. I have sent login info for the test to Shaun and Jason through the forums.

**Comment by splittingred** [comment]
splittingred submitted:

Ok, I can replicate it on that environment. I've narrowed it down to something in modx.panel.resource.static.js, around line 137:

<pre>var str = data.fullRelativeUrl;
str = str.replace(MODx.config.base_url,'');
if (str.substring(0,1) == '/') str = str.substring(1);
Ext.getCmp('modx-resource-content').setValue(str);</pre>

Somewhere, that code is wrong. I'm guessing the str.replace line, but I know that line is there for a reason, however. I'll take a look at it in the AM.

(Edit: ah, it's b/c your MODx.config.base_url == /, which means the first / is stripped, which means the one after assets/. That line of code should check to only run if MODx.config.base_url != / - I will fix it in the AM.)

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/56492710ee7b7079fbf8230e44a747307c09365a

(Mainly in the modx.panel.resource.static.js file; the other stuff is for getting the Browser to properly open to the right dir on click.)
