### ISSUE TITLE
Placeholders only inside of output filters not being processed.

### ISSUE THREAD

**Issue by yoleg** [modxbot/migrate#4712]
yoleg created Redmine issue ID 4712

I am posting this as a new bug report because my original bug report had too many errors in it and has already been closed: [[http://bugs.modx.com/issues/4638]]

This bug is hard to spot, because it only affects nested placeholders that don't otherwise exist without nesting. 

_Instructions:_ Create a chunk called TestChunk and call it with @[[$TestChunk? &name=`hello_world`]]@

Here is an example of a working TestChunk:

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucwords]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

Not working example 1 (only thing changed is line 5: changed ucwords to ucase - this breaks lines 2 and 4, which were not changed):

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords]]`]]
<br />Not Nested w/ OF: [[+name:replace=`_== `:ucase]]
<br />Not Nested w/ OF 2: [[+name:default=`Hello World`]]
<br />Simplest: [[+name]]
</pre>

Example 1 result:

<pre>
Nested Deeply: hello_world 
Nested Deeply w/ OF: 
Nested Once: hello_world 
Nested Once w/ OF: 
Not Nested w/ OF: HELLO WORLD 
Not Nested w/ OF 2: hello_world 
Simplest: hello_world
</pre>

Not working example 2 (only thing changed is deleted the bottom 3 lines - this breaks the top 4 lines):

<pre>
Nested Deeply: [[+message:default=`[[+label:default=`[[+name]]`]]`]]
<br />Nested Deeply w/ OF: [[+message:default=`[[+label:default=`[[+name:replace=`_== `:ucwords]]`]]`]]
<br />Nested Once: [[+label:default=`[[+name]]`]]
<br />Nested Once w/ OF: [[+label:default=`[[+name:replace=`_== `:ucwords]]`]]
</pre>

Example 2 result: 

<pre>
Nested Deeply: 
Nested Deeply w/ OF: 
Nested Once: 
Nested Once w/ OF:
</pre>

Please try the examples above and see if they break for you.

**Comment by opengeek** [comment]
opengeek submitted:

The problem is with the output filter parsing—it is unable to handle nested filters/modifiers that appear within tags nested within other filters/modifiers. Work is in progress to resolve this.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Could this be related to the issue I posted here? http://bugs.modx.com/issues/4894

In this case I am also using nested output modifier.

**Comment by opengeek** [comment]
opengeek submitted:

Yes Mike, these are the same issue, with nested output filters. The regex used to parse the output filters breaks if you nest filters within a filter modifier.

**Comment by gadamiak** [comment]
gadamiak submitted:

Is there any progress on this issue? Multiple @`]]@ are breaking my output and using some logic based on nested placeholders fails.

**Comment by opengeek** [comment]
opengeek submitted:

I believe this is resolved already for both 2.1 and 2.2. Can someone confirm my tests?

**Comment by opengeek** [comment]
opengeek submitted:

Jason Coward wrote:

> I believe this is resolved already for both 2.1 and 2.2. Can someone confirm my tests?

Likely was fixed by #5152

**Comment by freelancewebdev** [comment]
freelancewebdev submitted:

Still seeing this in or something that looks a lot like it in 2.2 pl2 I'm afraid:

Have inherited a site that had:

<code>

<pre>
[[+parent:eq=`189`:then=``:else=`<a href="[[~[[+id]]]]">
    <img src="[[!+news_image:eq=``:then=`/images/blog-post-image-1.jpg`:else[[+new_images:phpthumbof=`w=128&h=128&zc=1`]]`]]" width="128" height="128" class="bloglistimg" alt="[[+pagetitle]]" title="[[+pagetitle]]" /></a>
    `]]
</pre>

</code>
This was working on 2.1 pl - allegedly - not in 2.2 pl2.  Tried every possible configuration.  For now I have to forgo the phpthumbof - didn't even work when I moved the phpthumbof call out into a snippet to avoid having to pass it the parameters so now I have:
<code><pre>
[[+parent:eq=`189`:then=``:else=`<a href="[[~[[+id]]]]">
    <img src="[[!+news_image:default=`/images/blog-post-image-1.jpg`]]" width="128" height="128" class="bloglistimg" alt="[[+pagetitle]]" title="[[+pagetitle]]" /></a>
    `]]
</pre></code>

**Comment by freelancewebdev** [comment]
freelancewebdev submitted:

I should add that I'm pretty sure this isn't an issue with phpthumbof as I see some of the tag code output in the HTML which seems to suggest its the parsing that's broken.

**Comment by christianseel** [comment]
christianseel submitted:

_deleted by myself_
