### ISSUE TITLE
context specific filemanager path/url settings

### ISSUE THREAD

**Issue by mschlegel** [modxbot/migrate#4785]
mschlegel created Redmine issue ID 4785

I encountered a problem when trying to set up a separate assets folder for each subdomain 
I used the a different domain from a folder outside the modx root (tutorial: http://rtfm.modx.com/display/revolution20/Creating+a+Subdomain+from+a+Folder+using+Virtual+Hosts).

My system settings:
    filemanager_path = assets/
    filemanager_path_relative = Yes
    filemanager_url = assets/
    filemanager_url_relative = Yes

Context settings for subdomain
    filemanager_path = /var/www/path/subdomain/folder/assets/
    filemanager_path_relative = No
    filemanager_url = http://subdomain.org/assets/
    filemanager_url_relative = No

When trying to set a image or file TV  in the subdomain context, the folder structure as I had expected, but the containing files are not shown. The file tree right to "resources" and "elements" shows the files, but preview is broken. Uploading of files does not work either.
I believe there is a bug, because when I try to insert an image into TinyMCE, everything works as expected. I hope I'm not overseeing something obvious.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed mostly here: https://github.com/modxcms/revolution/commit/93cdccc77fb8f0f5847b2f05a3e7d71b0f2cbeb1

The rest I couldn't replicate, so assuming that's been fixed since rc4.

**Comment by mschlegel** [comment]
mschlegel submitted:

Thanks a lot! 
Got the standard filetree working with your modifications. The TV filemanger indeed only works for me in the git snapshot...

**Comment by mschlegel** [comment]
mschlegel submitted:

Sorry for being so late, but I would like to report that I still have some problems in Revolution-2.1.0-pl with the setup described above. The filemanager of the file TV gives me an error and shows a duplicated path:
/var/www/path/subdomain/folder/var/www/path/subdomain/folder/assets/

For me, the problem was fixed when applying the same modifications made to "core/model/modx/processors/element/tv/renders/mgr/input/image.php" to "file.php" too (see https://github.com/modxcms/revolution/commit/339e48924940de516a5a624983c134eb02983c00).

Another issue is, that in 2.1rc4, the image preview of TinyMCE in non-standard-contexts was fine, while it seems broken in 2.1.0-pl. However, on the webpage itself, the image is still shown correctly. I don't know, maybe I should report this elsewhere...

I encountered a third issue when trying to assign a "base path" and a "base url" (I hope that are the right english terms) directly in the image TV input options, so that I could only show the image folder (assets/images/) of the respective context.

I tried several settings, e.g.: 
base path: assets/images/ (relative: yes)
base url: assets/images/ (relative: yes)
or 
base path: @[[++assets_path]]/images/@ (relative: no)
base url: @[[++assets_url]]/images/@ (relative: no)
or 
base path: @[[++base_path]]/assets/images/@ (relative: no)
base url: @[[++base_url]]/assets/images/@ (relative: no)

but I always end up in the assets/images folder of the standard web context, although [[++assets_path/url]] and [[++base_path/url]] seem to be set to the correct, context specific paths.
I apologize in advance, if I misunderstood some concepts concerning these TV input options.
Cheers
