### ISSUE TITLE
Allow TV label "Categories" to be deactivable when using vertical tabs

### ISSUE THREAD

**Issue by lossendae** [modxbot/migrate#5933]
lossendae created Redmine issue ID 5933

For beginners the label "Categories" may be useful, but if i need to show the CMS to a customer, i would like to hide this label and keep the vertical tabs as minimalist as possible.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/2b744f730d12ec4a224873788c2f5da9e395f0e1

Rebuild/upgrade required for Git users.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Just upgraded to the latest nightly and changed "setting_show_tv_categories_header" to "No". However, I am still seeing the "Categories" header on my Resource TVs? (fyi, Mac / Firefox 8) 

@MODx.config.show_tv_categories_header@ is definitely "0", but the Categories html is still present.

When I made the following change, it seemed to work as expected:

@html: ( MODx.config.show_tv_categories_header == true ) ? '<h4 id="modx-resource-vtabs-header-title">'+_('categories')+'</h4>' : ''@
