### ISSUE TITLE
sources.modFileMediaSource not a subclass of sources.modMediaSource error

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#5970]
pixelchutes created Redmine issue ID 5970

I'm running a very recent nightly and started noticing the following error showing up in the MODx Error log:

@Instantiated a derived class sources.modFileMediaSource that is not a subclass of the requested class sources.modMediaSource@

I am not personally using Media Sources yet, and have left everything as "default" so far. However, I am seeing 10 to 20 of this exact same error message in the MODx error.log

FWIW, I noticed that once the page is cached, these errors do not show up...

Originated as forum post here: http://forums.modx.com/thread/71290/revolution-2-2-0-dev---modmediasource-error-log

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Oops, can you please update the "Affects Revolution Version" to 2.2.0 (not 2.1.3)

**Comment by MarkH** [comment]
markh submitted:

Also getting that on soon-to-be-production setup (crazy, perhaps, but that site desperately needed media sources and less techy UI so I'm taking the bet) on a live server, though I've been playing with sources a bit and it was an update from 2.1.3 with one TV that had base options set. 

Not getting these errors on a local install though where I haven't messed it about yet. Was assuming I goofed up something.

**Comment by splittingred** [comment]
splittingred submitted:

Haven't gotten this in a while; likely fixed with the recent xPDO fixes. Closing until can be confirmed through reproduction.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Just upgraded to 2.2.0-rc1 (advanced), but am still seeing these :(

@[2011-11-17 20:51:22](ERROR at /index.php) Instantiated a derived class sources.modFileMediaSource that is not a subclass of the requested class sources.modMediaSource
[2011-11-17 20:51:23](ERROR at /index.php) Instantiated a derived class sources.modFileMediaSource that is not a subclass of the requested class sources.modMediaSource
[2011-11-17 20:51:24](ERROR at /index.php) Instantiated a derived class sources.modFileMediaSource that is not a subclass of the requested class sources.modMediaSource@

**Comment by MarkH** [comment]
markh submitted:

I still have these issues as well, and just noticed that the values of an image TV using a file media source are not showing up.

It works in the front-end (the image value loads), but in the manager on the update page it's not showing any value. If this is related (and I'm guessing it is) I'm tempted to call that a blocker bug now... 

The data is available in the database, it stores the path there without the base_url of the media source which seems fine to me. That's also the value it shows when I select an image in the manager.

I'd love to fix this but I don't know where to look...

**Comment by MarkH** [comment]
markh submitted:

Oh, that's on rc1  btw. After going through a bunch of nightlies I haven't updated since the rc1 update. 

I see some  sanity checks being added in the past few days - think it would be worthwhile to update to the latest nightly and see if it's better with that?

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Hey Mark, good find. FWIW, I can confirm I am using Image TVs / GalleryItem in both instances where I'm still seeing these errors. Perhaps it is related as you suggest...

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in xPDO here: https://github.com/modxcms/xpdo/commit/80041c595a67a665b95fe397b44b0182125b01dc

Awaiting integration into revolution git branch.
