### ISSUE TITLE
No confirmation that "Clear error log" has worked with large error log

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#6970]
ncrossland created Redmine issue ID 6970

When you have a large error log, Reports-> Error Log displays a link to download the error log file instead.

If you click "clear", the log file is deleted on the server, but there is no confirmation that the file has been deleted, and the download button remains. 

Expected: After clicking clear, the download button and text should be replaced with the empty text field, as it is when clearing a smaller error log.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/4aa73bc2e7f68a0eaf33e5918ad58f01d8c2dd91

**Comment by christianseel** [comment]
christianseel submitted:

Issue still exists for me in the latest nightly.
