### ISSUE TITLE
Lack of cURL disallows use of local packages

### ISSUE THREAD

**Issue by yurkobb** [modxbot/migrate#7066]
yurkobb created Redmine issue ID 7066

Dear MODx maintainers,

I believe we need to amend current cURL warning behavior to block only the download function of package manager, while allowing the "Search locally for packages" functionality. Also, the current curl warning breaks the layout and makes the bottom of the package manager impossible to reach if display is not big enough (screenshot attached).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/e5a58f95572c719cdde2e0d714e0f7570c0dd6c8

**Comment by yurkobb** [comment]
yurkobb submitted:

Thank you!

**Comment by yurkobb** [comment]
yurkobb submitted:

Unfortunately the layout problem remains relevant: the curl warning pushes the scrollable package manager div down so that pm's bottom part is cut off along with scroll bar.The possible fix would be to somehow incorporate the warning div into the scrollable one. A screenshot is attached.
