### ISSUE TITLE
Server Error 500 with: modx.user.id:memberof

### ISSUE THREAD

**Issue by vitalized** [modxbot/migrate#7446]
vitalized created Redmine issue ID 7446

I've had a look but can't find this issue submitted before.
When using the call modx.user.id:memberof the server give a error 500 in the HTTP header.  The pages still load so it's not obvious unless you use something like "Web Inspector" in Safari Dev tools and monitor the "Network" tab.

I've tried this on two different servers and get the same error. Here's an example call:

<pre>
[[!+modx.user.id:memberof=`NameOfGroup`:then=`Yes`:else=`No`]]
</pre>

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/b8a4585df23724fac9b38b5a7dce3db78f8bf2a6

**Comment by vitalized** [comment]
vitalized submitted:

 I've updated the modoutputfilter.class.php with the code from Github. Still not fixed on two installations I've tried it on.

**Comment by splittingred** [comment]
splittingred submitted:

I copy+pasted this exact call:

<pre>[[!+modx.user.id:memberof=`NameOfGroup`:then=`Yes`:else=`No`]]</pre>

into my MODX installation with that code, and it worked fine. Perhaps something else is the issue with your system?

**Comment by vitalized** [comment]
vitalized submitted:

It says "Fixed" and gives a URL of a 'commit'. Did you see the issue then fix it?

**Comment by splittingred** [comment]
splittingred submitted:

Yes, I did, according to the reproduction data that you gave me. The commit fixes the issue of notice errors appearing on my installation.

If you are still experiencing an issue, you should provide more information as to how the issue is occuring, as well as any debugging information you could provide.

**Comment by freelancewebdev** [comment]
freelancewebdev submitted:

This issue is still hanging round like a bad smell in 2.2.2-pl.  Anonymous user causes 500 error headers but page still renders - kills use of firebug etc though.

**Comment by freelancewebdev** [comment]
freelancewebdev submitted:

Also just checked an installation of 2.2.4-pl - also happening there.  When a user is not logged in, the page is returned but with a 500 status code in the header - check the network tab in firebug or Chrome Dev Tools to see.

**Comment by goldsky** [comment]
goldsky submitted:

try this:

<pre>
[[!+modx.user.id:memberof=`NameOfGroup`:is=`1`:then=`Yes`:else=`No`]]
</pre>

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this at all. Placing the original line in a page logged in or not does not cause the page to return a 500 response.
