### ISSUE TITLE
Directory connector request timeout

### ISSUE THREAD

**Issue by Jsewill** [modxbot/migrate#8105]
jsewill created Redmine issue ID 8105

  When attempting to view files from the files tree or "MODx browser" nothing shows up.  The request sent to connectors/browser/directory.php times out.  More might happen, but all I get is a timeout (reminds me of childhood--not my own of course ;-) ).

**Comment by Jsewill** [comment]
jsewill submitted:

  So far, I've narrowed it down to modfilemediasource.class.php: line 96-ish...$bases = $this->getBases($path);

  I'll dig a little further and see what I can find.

**Comment by Jsewill** [comment]
jsewill submitted:

Found it.  There's a never ending while loop.  core/model/modx/modfilehandler.class.php: line 113:

public function sanitizePath($path) {
        $replace = array('../' => '', './' => '', '\' => '/', '//'  => '/');
        foreach ($replace as $from => $to) {
            while (stristr($from,$path)) {
                $path = str_replace($from,$to,$path);
            }
        }
        return $path;
    }

  I'll see about making a pull request...that is when I figure out for sure how this is supposed to work.

**Comment by Jsewill** [comment]
jsewill submitted:

Sent pull request with a fix.  Simply removing the while loop should fix this issue.  Worked perfectly using the default (/) and subdirectory-based file media sources.  See pull request:  https://github.com/modxcms/revolution/pull/328

**Comment by gadgetto** [comment]
gadgetto submitted:

I have the same problem after updating to 2.2.3. So I implemented your fix but it still doesn't work. No files are listed under file tree.

Server log says:
"connectors/browser/directory.php?action=getList&id=/ HTTP/1.1" 500 411

I also posted the problem in the forum:
http://forums.modx.com/thread/77261/latest-update-revo-2-2-3-pl-breaks-file-listings-under-file-tab#dis-post-426634

**Comment by gadgetto** [comment]
gadgetto submitted:

Here is the right fix for now:
http://tracker.modx.com/issues/8051#change-17858

Bug is set to version 2.2.4

**Comment by opengeek** [comment]
opengeek submitted:

Shaun reverted the PR which caused this bug here for now: https://github.com/modxcms/revolution/commit/975675e604da58da8db011dd4ffb9ddf2a77ad39

I am reviewing for a solution that achieves what the PR was attempting but works properly.

**Comment by Jsewill** [comment]
jsewill submitted:

If my pull request won't work, let me know so I can close it.  Also, for clarification, what was the pull request in question attempting to achieve?

**Comment by opengeek** [comment]
opengeek submitted:

New solution without the infinite recursion issue here:

https://github.com/modxcms/revolution/commit/10248d06ebb7c933d33129272623d0a64d528a82

Will release 2.2.4-pl shortly since this is a critical issue.
